# This file contains unified settings for tabular datasets used in LiRA attacks

seed: 42
use_cuda: true

dataset:
  name: purchase # Options: purchase, texas, locations 
  num_classes: 100 # Options: 100, 100, 30
  data_dir: data
  pkeep: 0.5

train_data_augmentation: []

model:
  architecture: fcn
  input_dim: 600 # Options: 600, 6169, 446
  hidden_dims: [1024, 512] # e.g., [1024, 512, 256, 128]
  drop_rate: 0.0
  activation: tanh
  pretrained: false

training:
  num_shadow_models: 20
  epochs: 20
  batch_size: 128
  num_workers: 4
  learning_rate: 0.01
  weight_decay: 5e-4
  momentum: 0.9
  lr_scheduler: cosine
  lr_step_size: 30
  save_step: 10
  save_models: true
  lr_gamma: 0.1
  early_stopping: true
  patience: 20
  resume: false

experiment:
  log_level: info
  checkpoint_dir: none #Options: none or directory to load checkpoints for resume training and/or attack (e.g., experiments/cifar10/wrn28-2/2025-05-12_0056)


# datasets:
#   purchase:
#     name: purchase
#     num_classes: 100
#     input_dim: 600
#     data_dir: data
#     pkeep: 0.5

#   texas:
#     name: texas
#     num_classes: 100
#     input_dim: 6169
#     data_dir: data
#     pkeep: 0.5

#   location:
#     name: location
#     num_classes: 30
#     input_dim: 446
#     data_dir: data
#     pkeep: 0.5
