
# Attack configuration
attack:
  method: [lira]  # Options: none, lira, rmia, both. LiRA is the only implemented attack right now.

  # Evaluation mode options:
  # - 'single': Original mode using ntest models as targets (default)
  # - 'leave_one_out': Evaluate using each model as target, report mean±std
  # - 'both': Run both evaluation modes
  evaluation_mode: 'both'  

  save_hard_labels: true  # Whether to save hard labels for the attack
  save_attack_predictions: true  # Whether to save attack likelihood ratios
  
  # Number of test models (only used when evaluation_mode='single' or 'both')
  ntest: 1

  # Metric to display in plots ('auc' or 'acc')
  plot_metric: 'auc'
  target_fprs: [0.00001, 0.001]  # Target false positive rates for the attack
  prior: 0.5  # Prior probability of membership
  target_model: best  # Options: epoch, best
  

# INFERENCE augmentations for LiRA (deterministic, different from training)
inference_data_augmentations:
  type: 'spatial'  # Options: 'none', 'horizontal_flip', 'spatial'
  spatial_shift: 2  # Number of pixels to shift (0 for no spatial shifts)
  spatial_stride: 2  # Stride for spatial grid (1 = all positions, 2 = every other, etc.)
  horizontal_flip: true  # Whether to include horizontal flips
  

save_results: true
visualize: true

# Experiment configuration
experiment:
  log_level: info
  checkpoint_dir: experiments/cifar10/resnet18/2025-10-22_2249  #Options: none to start from scratch or directory to load checkpoints for resume training and/or attack (e.g., experiments/cifar10/wrn28-2/2025-05-12_0056)
  overwrite_logits: false  # Whether to overwrite logits
  overwrite_scores: false  # Whether to overwrite scores

